name = "palm-mystic-api"
main = "workers/api.ts"
compatibility_date = "2024-01-01"

# DB 연결 비활성화로 인해 환경변수 불필요
# wrangler secret put DATABASE_URL
# wrangler secret put ADMIN_PASSWORD  
# wrangler secret put SENDGRID_API_KEY
